name: DEPLOY

on:
  workflow_dispatch:
    inputs:
      deploy_commit:
        required: true
      app_name:
        required: true

jobs:
  deploy:
    uses: raghudevopsb79/roboshop-github-reuseable-actions/.github/workflows/app-deploy.yaml@main
    with:
      deploy_commit: ${{ github.event.inputs.deploy_commit }}
      app_name: ${{ github.event.inputs.app_name }}
